server.port=8081


# ???????
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/groupdata?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.url=jdbc:postgresql://192.168.0.104:5432/groupdata?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username=postgres
spring.datasource.password=postgres

# ????????

# hikari?????
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
#??????????10???0???maximum-pool-size??????maximum-pool-size
spring.datasource.hikari.minimum-idle=10
#??????????0????????10??????1?????minimum-idle??
spring.datasource.hikari.maximum-pool-size=20
#????????????600000?10????????max-lifetime?max-lifetime>0??????0????0???10???????10?
spring.datasource.hikari.idle-timeout=500000
#????????????0???30??????????30??.?????mysql????????
spring.datasource.hikari.max-lifetime=540000
#????????????250????????????30?
spring.datasource.hikari.connection-timeout=60000




## druid?????
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
## druid???????
##???????/??/??
#spring.datasource.initialSize=5
#spring.datasource.minIdle=1
##spring.datasource.maxIdle=20
#spring.datasource.maxActive=100
##??????????
#spring.datasource.maxWait=60000
##??????????????????????
#spring.datasource.timeBetweenEvictionRunsMillis=60000
##??????????????
#spring.datasource.minEvictableIdleTimeMillis=300000
## ??????????? sql ????????, ?? oracle ???? SELECT 1 FROM DUAL
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
## ????? true????????????????????????????????? timeBetweenEvictionRunsMillis??? validationQuery ????????
#spring.datasource.testWhileIdle=true
## ??????? validationQuery ?????????????????????
#spring.datasource.testOnBorrow=false
## ??????? validationQuery ?????????????????????
#spring.datasource.testOnReturn=false
##??PSCache?????????PSCache????oracle??true?mysql??false????????????false
#spring.datasource.poolPreparedStatements=false
##???PSCache???????0????0??poolPreparedStatements???????true??Druid??????Oracle?PSCache??????????????????????????100
#spring.datasource.maxPoolPreparedStatementPerConnectionSize= 20
## stat,wall,log4j
#spring.datasource.filters=stat
#spring.datasource.useGlobalDataSourceStat=true
## ??connectProperties?????mergeSql????SQL??
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#spring.druid.validationQuery=select 1


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.tomcat.max-http-header-size=81920